### ISSUE TITLE
 tweet_processor.set_options(tweet_processor.OPT.URL, AttributeError: module 'preprocessor' has no attribute 'set_options'

### ISSUE THREAD

**Issue by Jyothsna2795** [motazsaad/tweets-collector#4]
Following error occurred while running json2text.py..............please help out 

 python json2text.py -i C:\\Users\\jyo27\\my_work\\tweets-collector -o C:\\Users\\jyo27\\my_work\\tweets-collector\\tweet_output
extract tweets from C:\Users\jyo27\my_work\tweets-collector\out.json
tweets in json file: 15 tweets
Traceback (most recent call last):
  File "json2text.py", line 105, in <module>
    extract_tweets_from_json_files(json_dir, out_dir)
  File "json2text.py", line 93, in extract_tweets_from_json_files
    extract_tweets_from_json(json_reader, text_writer)
  File "json2text.py", line 46, in extract_tweets_from_json
    text = tweet_cleaner.clean_tweet(text)
  File "C:\Users\jyo27\my_work\tweets-collector\tweet_cleaner.py", line 135, in clean_tweet
    tweet_processor.set_options(tweet_processor.OPT.URL,
AttributeError: module 'preprocessor' has no attribute 'set_options'

**Comment by Amani1Dridi** [comment]
hi ! if u find a solution thank u to share with me !

**Comment by gordeli** [comment]
This happens because you have both preprocessor and tweet-preprocessor libraries installed per your requirements.txt file. Both contain the module preprocessor and the one from the preprocessor library is not the one you want. Uninstall the preprocessor library and this should solve the problem.
